AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Application:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS


  CertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${Application}/certificate-arn
      Description: !Sub ${Application} certificate Arn
      Type: String
      Value: !Ref Certificate 

Outputs:
  CertificateArn:
    Description: The Certificate ARN
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-CertificateArn