name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
   
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/LambdaMinimalApiSample
 

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release
      
    - name: Zip artifact
      run: |
        zip -jr lambdaminimalapisample.zip  ./LambdaMinimalApiSample/bin/Release/net6.0/publish
      

    - uses: actions/upload-artifact@v3
      with:
        name: lambdaminimalapisample
        path: ./src/LambdaMinimalApiSample/lambdaminimalapisample.zip
        
  publish-to-s3:
    needs: [build-and-publish]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: lambdaminimalapisample
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Create or update lambda bucket
      run: |
        aws cloudformation deploy --template-file ./aws/cfn/lambda-bucket.yml --stack-name lambda-bucket --parameter-overrides LambdaBucketName=minimal-api-lambda-sample-bucket
        
    - name: Upload to S3
      run: |
        aws s3 cp lambdaminimalapisample.zip s3://minimal-api-lambda-sample-bucket

  deploy-to-dev:
    needs: [publish-to-s3]
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Deploy lambda
      run: |
        aws cloudformation deploy --template-file ./aws/cfn/minimal-api-lambda.yml --stack-name minimal-api-lambda-sample --parameter-overrides \
            Application=minimal-api-sample \
            Environment=dev \
            LambdaName=lambda \
            LambdaHandler=LambdaMinimalApiSample \
            LambdaBucketName=minimal-api-lambda-sample-bucket \
            LambdaZipFile=lambdaminimalapisample.zip
           